### ISSUE TITLE
python2.7在centos下导入paramiko报错

### ISSUE THREAD

**Issue by TimeBoat** [cksgf/ServerManagement#2]
flask.cli.NoAppException
flask.cli.NoAppException: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/irona/Documents/Python/vpn_manager/app.py", line 4, in <module>
    from route.login import cklogin
  File "/home/irona/Documents/Python/vpn_manager/route/__init__.py", line 1, in <module>
    from . import file
  File "/home/irona/Documents/Python/vpn_manager/route/file.py", line 3, in <module>
    from index import app
ImportError: No module named 'index'

Traceback (most recent call last)
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 325, in __call__
self._flush_bg_loading_exception()
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
reraise(*exc_info)
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 302, in _load_app
self._load_unlocked()
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 317, in _load_unlocked
self._app = rv = self.loader()
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 372, in load_app
app = locate_app(self, import_name, name)
File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 242, in locate_app
'\n\n{tb}'.format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "app", an ImportError was raised: Traceback (most recent call last): File "/home/irona/Documents/Python/vpn_manager/venv/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app __import__(module_name) File "/home/irona/Documents/Python/vpn_manager/app.py", line 4, in <module> from route.login import cklogin File "/home/irona/Documents/Python/vpn_manager/route/__init__.py", line 1, in <module> from . import file File "/home/irona/Documents/Python/vpn_manager/route/file.py", line 3, in <module> from index import app ImportError: No module named 'index'

**Comment by TimeBoat** [comment]
小白第一次用flask求指教

**Comment by cksgf** [comment]
加我qq吧，我教你。。2986715422

**Comment by cksgf** [comment]
程序入口文件名字应该为index.py，不要修改，如果改了的话，需要把route下所有的文件中，from index import 做相应的变更

**Comment by TimeBoat** [comment]
> 改成python2.7并在centos下运行的话，如果出现导入paramiko报错的情况，执行下`yum install python-paramiko -y`

貌似并不是简单的导入问题，我还是晚点加你QQ沟通吧，感谢～

**Comment by cksgf** [comment]
哎？？？？加我qq的那个人不是你吗？我以为是你。。。

**Comment by cksgf** [comment]
> > 改成python2.7并在centos下运行的话，如果出现导入paramiko报错的情况，执行下`yum install python-paramiko -y`
> 
> 貌似并不是简单的导入问题，我还是晚点加你QQ沟通吧，感谢～
